CREATE TABLE sri (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ingested_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, data jsonb NOT NULL);

-- CREATE INDEX CONCURRENTLY IF NOT EXISTS idxdata ON public.sri USING GIN (data);
-- To reduce the index size, only index the fields we query
CREATE INDEX CONCURRENTLY IF NOT EXISTS idxdata_hashes_pathops ON public.sri USING GIN ((data->'hashes') jsonb_path_ops);

-- CREATE USER api WITH ENCRYPTED PASSWORD 'sri_api_user';
CREATE ROLE api_anonymous WITH NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT SELECT ON public.sri TO api_anonymous;

CREATE OR REPLACE FUNCTION find_component_by_hash(hash TEXT)
RETURNS TABLE (component text, version text) AS $$
DECLARE
  hash ALIAS FOR $1;
  sql text;
BEGIN
sql = E'SELECT data ->> \'component\' AS component, data ->> \'version\' AS version FROM sri WHERE data->\'hashes\' @> \'[{"sha256": "' || hash || E'"}]\'';
RETURN QUERY EXECUTE sql;
END; $$
LANGUAGE 'plpgsql' STABLE STRICT LEAKPROOF PARALLEL SAFE;
